import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { topic } = await req.json();
    
    if (!process.env.GROQ_API_KEY) {
      return NextResponse.json({ error: 'Groq API Key is missing.' }, { status: 500 });
    }

    const { OpenAI } = await import('openai');
    const openai = new OpenAI({
      apiKey: process.env.GROQ_API_KEY,
      baseURL: 'https://api.groq.com/openai/v1',
    });

    const prompt = `You are an expert Ayurvedic doctor and SEO content writer. Write a comprehensive, SEO-optimized blog post about "${topic || 'Ayurvedic wellness'}". 
The post should be structured with markdown headings (##, ###). Include practical tips, natural ingredient recommendations (like Ashwagandha, Brahmi), and promote a holistic lifestyle. Return ONLY the markdown content, no pleasantries or introductions. Keep it around 400-500 words.`;

    const response = await openai.chat.completions.create({
      model: 'llama-3.1-8b-instant',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 1500,
    });

    const generatedContent = response.choices[0]?.message?.content || "Failed to generate content.";
    const fallbackTitle = topic ? `The Complete Guide to ${topic}` : "10 Ayurvedic Secrets for a Balanced Life";

    const mockBlog = {
      id: `blog_${Date.now()}`,
      title: fallbackTitle,
      slug: topic ? `guide-to-${topic.toLowerCase().replace(/[^a-z0-9]+/g, '-')}` : "ayurvedic-secrets",
      excerpt: "Discover ancient wisdom combined with modern wellness techniques to elevate your daily routine.",
      content: generatedContent + "\n\n*This post was automatically generated by the Nexus OS SEO Intelligence Engine and is pending your approval.*",
      author: "AI Co-Pilot",
      status: "pending",
      createdAt: new Date().toISOString()
    };

    return NextResponse.json({ success: true, blog: mockBlog });
  } catch (error: any) {
    console.error('Blog Generation Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
